import "./globals.css";
import { mainFont } from "@/lib/font";

export const metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased scroll-smooth}`}>
        {children}
      </body>
    </html>
  );
}
