import React from "react";
export const metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="bg-light-bg dark:bg-custom-black-400 flex-1  ">
      <div></div>
    </div>
  );
}
